apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |-
    .:53 {
        log
        errors
        health {
            lameduck 5s
        }
        ready
        etcd ̣{{.Values.domain}} {
            stubzones
            path /skydns
            endpoint http://{{.Values.clusterip}}:{{.Values.etcport}}
        }
        cache 30
        loop
        reload
        loadbalance
    }
