apiVersion: v1
kind: Service
metadata:
  name: coredns-coredns
  labels:
    app.kubernetes.io/name: coredns
spec:
  selector:
    app.kubernetes.io/name: coredns
  ports:
  - name: udp-53
    port: 53
    protocol: UDP
    targetPort: 53
  - name: tcp-53
    port: 53
    protocol: TCP
    targetPort: 53
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  labels:
    app.kubernetes.io/name: coredns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: coredns
  template:
    metadata:
      labels:
        k8s-app: coredns
        app.kubernetes.io/name: coredns
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: default
      dnsPolicy: Default
      containers:
      - name: "coredns"
        image: "coredns/coredns:1.9.4"
        imagePullPolicy: IfNotPresent
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 53 
          name: udp-53
        - containerPort: 53 
          name: tcp-53
        - containerPort: 9153 
          name: tcp-9153

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile