
#namespace: NAMESPACE
letsencrypted: false
env: "prod"
branch: "prod"
branchenv: "prod"
revision: ""
ressources:
  enable: false
  totalstorage: "10Gi"
filestore:
  storage: 5Gi
postgres:
  password: PG_RANDOM_PASSWORD
  imageversion: postgres:15
  storage: 5Gi
  cpurequest: 1
  cpulimit: 3
  memoryrequest: 1Gi
  memorylimit: 4G
tlscert: ""
tlskey: ""
s3object:
  bucketname: ""
  name: ""
  provider: ""
  type: ""
  accesskey: ""
  secretkey: ""
  endpoint: ""

odoo: 
  imageversion: odoo:16
  subdomain: subdomain
  domain: domain.com
  extramodules: ""
  nativemodules: ""
  mainrepo: ""
  mainbranch: ""
  mainaddonsfolder: ""
  customgit: ""
  customgitbranch: ""
  maingittoken: ""
  customgittoken: ""
  deploymenthash: ""
  masterdbpass: ""
  backupcurrentdb: "NO"
  podcode: ""
  ingress:
    enabled: false
    email: ""
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: subdomain.domain
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
      - secretName: odoo-tls
        hosts:
        - subdomain.domain
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80