apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-ingress
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
    #kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: ingress-nginx
  defaultBackend:
    service:
      name: odoo-service
      port:
        number: 8069
  rules:
  {{- range .Values.odoo.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: odoo-service
              port:
                number: 8069
  {{- end }}
  
  tls:
  {{- range .Values.odoo.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}

                