apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
spec:
  hard:
    requests.cpu: {{.Values.postgres.cpurequest}}
    requests.memory: {{.Values.postgres.memoryrequest}}
    limits.cpu: {{.Values.postgres.cpulimit}}
    limits.memory: {{.Values.postgres.memorylimit}}
