{{- if eq .Values.env "base"}}
apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: "postgresql-pv-{{.Values.namespace}}"
  labels:
    type: local # Sets PV's type to local
spec:
  storageClassName: "pg-{{.Values.namespace}}"
  capacity:
    storage: {{.Values.postgres.storage}} # Sets PV Volume
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/data/{{.Values.namespace}}" # Sets the volume's path
{{- end}}