apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: {{.Values.namespace}}
  labels:
    app: odoo
data:
  ODOO_EXTRA_MODULES: {{.Values.odoo.extramodules}}
  ODOO_NATIVE_MODULES: {{.Values.odoo.nativemodules}}
  SERVER_WIDE_MODULES: {{.Values.odoo.serverwidemodules}}
  MAIN_GIT: {{.Values.odoo.mainrepo}}
  MAIN_GIT_BRANCH: {{.Values.odoo.mainbranch}}
  MAIN_GIT_TOKEN: {{.Values.odoo.maingittoken}}
  CUSTOM_GIT: {{.Values.odoo.customgit}}
  CUSTOM_GIT_BRANCH: {{.Values.odoo.customgitbranch | quote}}
  CUSTOM_GIT_TOKEN: {{.Values.odoo.customgittoken}}
  SAAS_MANAGER_URL: {{.Values.odoo.saasurl}}
  SAAS_SUBSCRIPTION_NUM: {{.Values.odoo.subscription}}
  SAAS_SUBSCRIPTION_TRIAL: {{.Values.odoo.trialmode}}
  SAAS_SUBSCRIPTION_ENDATE: {{.Values.odoo.enddate}}
  SAAS_DEPLOYMENT_HASH: {{.Values.odoo.deploymenthash}}
  BACKUP_CURRENT_DB: {{.Values.odoo.backupcurrentdb}}
  MASTERDB_PASSWORD: {{.Values.odoo.masterdbpass}}
  POD_CODE: {{.Values.odoo.podcode}}