apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: {{.Values.namespace}}
  labels:
    app: odoo
data:
  ODOO_EXTRA_MODULES: {{.Values.odoo.extramodules | quote }}
  ODOO_NATIVE_MODULES: {{.Values.odoo.nativemodules | quote }}
  SERVER_WIDE_MODULES: {{.Values.odoo.serverwidemodules | quote }}
  MAIN_GIT: {{.Values.odoo.mainrepo | quote }}
  MAIN_GIT_BRANCH: {{.Values.odoo.mainbranch | quote }}
  MAIN_GIT_TOKEN: {{.Values.odoo.maingittoken | quote }}
  CUSTOM_GIT: {{.Values.odoo.customgit | quote }}
  CUSTOM_GIT_BRANCH: {{.Values.odoo.customgitbranch | quote}}
  CUSTOM_GIT_TOKEN: {{.Values.odoo.customgittoken | quote }}
  SAAS_MANAGER_URL: {{.Values.odoo.saasurl | quote }}
  SAAS_SUBSCRIPTION_NUM: {{.Values.odoo.subscription | quote }}
  SAAS_SUBSCRIPTION_TRIAL: {{.Values.odoo.trialmode | quote }}
  SAAS_SUBSCRIPTION_ENDATE: {{.Values.odoo.enddate | quote }}
  SAAS_DEPLOYMENT_HASH: {{.Values.odoo.deploymenthash | quote }}
  BACKUP_CURRENT_DB: {{.Values.odoo.backupcurrentdb | quote }}
  MASTERDB_PASSWORD: {{.Values.odoo.masterdbpass | quote }}
  POD_CODE: {{.Values.odoo.podcode | quote }}
  ODOO_DB: {{.Values.namespace}}