apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  labels:
    app: odoo
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      volumes:
      #- name: odooaddons
      #  hostPath:
      #    path: /odoo/addons/{{.Values.namespace}}  
      - name: odoo-data
        emptyDir:
          sizeLimit: 100Mi
      - name: addons-scripts
        configMap:
          name: addons-scripts
          defaultMode: 0777
      containers:
      - name: odoo
        image: {{.Values.odoo.imageversion}}
        volumeMounts:
        #- name: odooaddons
        #  mountPath: /mnt/extra-addons
        - name: addons-scripts
          mountPath: /mnt/scripts
        - name: odoo-data
          mountPath: /mnt/data
        ports:
        - containerPort: 8069
        command: ["bash", "/mnt/scripts/run.sh"]
        #args: ["/mnt/scripts/global_addons_import.sh;/mnt/scripts/custom_addons_import.sh;/mnt/scripts/requirements.sh"]
        envFrom:
          - configMapRef:
              name: odoo-config
        env:
        - name: HOST
          value: postgres-service.{{.Values.namespace}}.svc
        - name: USER
          value: odoo
        - name: PASSWORD
          value: {{.Values.postgres.password}}
        - name: ODOO_DB
          value: {{.Values.namespace}}