{{- if ne .Values.env "base"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment-{{.Values.branchenv}}
  labels:
    app: odoo
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
        hash: {{.Values.odoo.deploymenthash}}
        revision: {{.Values.revision}}
    spec:
      volumes:
      {{- if or (eq .Values.env "prod") (eq .Values.env "stage")}}
      - name: rclone-config
        secret:
          optional: false
          secretName: rclone-config
      - name: backup-scripts
        configMap:
          name: backup-scripts
          defaultMode: 0777
      - name: backup-data
        emptyDir:
          sizeLimit: 50Gi
      - name: restore-data
        emptyDir:
          sizeLimit: 50Gi
      - name: datadir
        persistentVolumeClaim:
          claimName: filestore-pvc
      {{- end}}
      
      - name: odoo-data
        emptyDir:
          sizeLimit: 500Mi
      - name: addons-scripts
        configMap:
          name: addons-scripts
          defaultMode: 0777
      - name: pvchecker-scripts
        configMap:
          name: pvchecker-scripts
          defaultMode: 0777
      {{- if or (eq .Values.env "prod") (eq .Values.env "stage")}}
      initContainers:
      - name: filestore-data-permission-fix
        image: busybox
        command: ["/bin/sh","-c","/scripts/pvchecker.sh"]
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/odoo
        - name: pvchecker-scripts
          mountPath: /scripts
      {{- end}}
      containers:
      {{- if or (eq .Values.env "prod") (eq .Values.env "stage")}}
      - name: odoo-backup
        image: tarcisse/saaspgtools:1.1
        command: ["bash", "/mnt/scripts/run_backup.sh"]
        
        volumeMounts:
        - mountPath: /config/rclone
          name: rclone-config
        - name: backup-data
          mountPath: /backup
        - mountPath: /restore
          name: restore-data
        - name: backup-scripts
          mountPath: /mnt/scripts
        - mountPath: /datadir
          name: datadir
        envFrom:
        - configMapRef:
            name: odoo-config-{{.Values.branchenv}}
        env:
        - name: BUCKET_NAME
          value: {{.Values.s3object.bucketname | quote }}
        - name: PROVIDER
          value: {{.Values.s3object.provider | quote }}
        - name: STNAME
          value: {{.Values.s3object.name | quote}}
      {{- end}}
      - name: odoo
        image: {{.Values.odoo.imageversion}}
        volumeMounts:
        - name: addons-scripts
          mountPath: /mnt/scripts
        - name: odoo-data
          mountPath: /mnt/data
        {{- if or (eq .Values.env "prod") (eq .Values.env "stage")}}
        - name: datadir
          mountPath: /var/lib/odoo
        {{- end}}
        ports:
        - containerPort: 8069
        command: ["bash", "/mnt/scripts/run.sh"]
        envFrom:
          - configMapRef:
              name: odoo-config-{{.Values.branchenv}}
        env:
        - name: HOST
          value: "postgres-service.{{.Values.namespace}}.svc"
        - name: USER
          value: odoo
        - name: PASSWORD
          value: {{.Values.postgres.password | quote}}
{{- end}}