{{- if eq .Values.env "base"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-scripts
  namespace: {{.Values.namespace}}
  labels:
    app: odoo-backup
data:
{{ (.Files.Glob "scripts/run_backup.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/postgres_backup.py").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/postgres_restore.py").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/postgres_manager.py").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/__init__.py").AsConfig | indent 2 }}
{{- end }}


