{{- if or (eq .Values.env "prod") (eq .Values.env "stage")}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-scripts
  namespace: {{.Values.namespace}}
  labels:
    app: odoo-backup
data:
{{ (.Files.Glob "scripts/run_backup.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/postgres_backup.py").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/postgres_restore.py").AsConfig | indent 2 }}
{{- end }}


