apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issue
spec:
  acme:
    email: {{.Values.odoo.ingress.email}}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: {{.Values.odoo.ingress.email}}
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token