apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: odoo-certificate
  namespace: {{.Values.namespace}}
spec:
  secretName: odoo-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  commonName: {{.Values.odoo.domain}}
  dnsNames:
  - {{.Values.odoo.domain}}
  - '*.{{.Values.odoo.domain}}'