{{- if eq .Values.env "base"}}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: {{.Values.odoo.ingress.cloudflaretoken}}
{{- end }}