{{- if eq .Values.env "base"}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "filestore-{{.Values.namespace}}"
provisioner: Local
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
{{- end}}