{{- if or (eq .Values.env "prod") (eq .Values.env "stage")}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-script-cm
data:
{{ (.Files.Glob "scripts/rclone_run.sh").AsConfig | indent 2 }}
{{- end }}