{{- if eq .Values.env "base"}}
apiVersion: v1
kind: Secret
metadata:
  name: rclone-config
  namespace: {{.Values.namespace}}
stringData:
  rclone.conf: |
    [{{.Values.s3object.name}}]
    type = {{.Values.s3object.type}}
    provider = {{.Values.s3object.provider}}
    access_key_id = {{.Values.s3object.accesskey}}
    secret_access_key = {{.Values.s3object.secretkey}}
    endpoint = {{.Values.s3object.endpoint}}
{{- end}}