{{- if or (eq .Values.env "prod") (eq .Values.env "stage")}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-script-cm
data:
S3BUCKET_NAME: {{.Values.s3object.bucketname}}
S3PROVIDER : {{.Values.s3object.provider}}
{{ (.Files.Glob "scripts/rclone_run.sh").AsConfig | indent 2 }}
{{- end }}