{{- if .Values.ressources.enable -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: subscription-resources
spec:
  hard:
    requests.cpu: {{.Values.postgres.cpurequest | quote}}
    requests.storage: {{.Values.postgres.storagerequest}}
    requests.memory: {{.Values.postgres.memoryrequest}}
    limits.cpu: {{.Values.postgres.cpulimit | quote}}
    limits.memory: {{.Values.postgres.memorylimit }}
{{- end}}