{{- if eq .Values.env "base"}}
{{- if .Values.ressources.enable -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: subscription-resources
spec:
  hard: 
    requests.cpu: {{.Values.postgres.cpurequest | quote}}
    requests.storage: {{.Values.resource.totalstorage | quote}}
    requests.memory: {{.Values.postgres.memoryrequest}}
    limits.cpu: {{.Values.postgres.cpulimit | quote}}
    limits.memory: {{.Values.postgres.memorylimit }}
{{- end}}
{{- end}}