{{- if eq .Values.env "base"}}
{{- if ne .Values.odoo.ingress.tlscert ""}}
apiVersion: v1
kind: Secret
metadata:
    name: odoo-tls
    namespace: {{.Values.namespace}}
data:
  tls.crt:  {{ .Values.tlscert | quote }}
  tls.key:  {{ .Values.tlskey  | quote }}
{{- end}}  
{{- end}}

