apiVersion: v1
kind: Config
clusters:
- name: "kubernetes-cluster"
  cluster:
    server: "https://kubernetes.default.svc"
    #certificate-authority-data: "[KUBERNETES-CERT-FILE]"
current-context: "microk8s"
contexts:
- name: "microk8s"
  context:
    user: "admin"
    cluster: "microk8s-cluster"
users:
- name: "admin"
  #user:
  #  token: "[KUBEADMIN-TOKEN]"
