
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: odoosaas-certificate
  namespace: cert-manager
spec:
  secretName: odoosaas-tls
  issuerRef:
    name: cloudflare-issue
    kind: ClusterIssuer
    secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "argocd,monitoring,default"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "argocd,monitoring,default" # Control auto-reflection namespaces
  commonName: {{.Values.domain}}
  dnsNames:
  - {{.Values.domain}}
  - '*.{{.Values.domain}}'
