
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: odoosaas-certificate
  namespace: cert-manager
spec:
  secretName: odoosaas-tls
  issuerRef:
    name: cloudflare-issue
    kind: ClusterIssuer
  commonName: {{.Values.domain}}
  dnsNames:
  - {{.Values.domain}}
  - '*.{{.Values.domain}}'
